### ISSUE TITLE
demo-box disapper after swtiching markdown files 

### ISSUE THREAD

**Issue by imyelo** [njleonzhang/docsify-demo-box-react#1]
[https://github.com/njleonzhang/docsify-demo-box-react/blob/5ca08e323466fb7eb5f65efb1b1c0dda287cc06a/src/plugin/index.js#L15](https://github.com/njleonzhang/docsify-demo-box-react/blob/5ca08e323466fb7eb5f65efb1b1c0dda287cc06a/src/plugin/index.js#L15)

It seem the ``renderer.code`` doesn't execute after switching files.

**Comment by njleonzhang** [comment]
fixed and release 1.0.1. please have a try

**Comment by imyelo** [comment]
It work as expected now. Thanks!

**Comment by njleonzhang** [comment]
Are you using this plugin to write a doc for some library? If yes, do you mind if I show your project in my readme as a sample？

**Comment by imyelo** [comment]
Of Course! With pleasure.

https://sodalife.github.io/soui-react/

**Comment by njleonzhang** [comment]
It's cool! 
 [更新了readme](https://github.com/njleonzhang/docsify-demo-box-react/blob/master/README.md#showcase) , 有时间学习下

另外通过`desc`可以给例子添加说明，你好像没用这个功能。不知道你是不是没注意，提醒下有这个功能。:)

 https://njleonzhang.github.io/docsify-demo-box-react/#/?id=sample

**Comment by imyelo** [comment]
Get √

确实没注意到 :+1:
